name: CSE Scraper Workflow

on:
  workflow_dispatch:
    inputs:
      company_code:
        description: 'Company stock symbol (e.g., HNB.N0000)'
        required: true
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Install Google Chrome for Selenium
        uses: browser-actions/setup-chrome@latest
        
      - name: Run the Python Scraper Script
        env:
          GDRIVE_SA_KEY: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
        run: python scraper.py "${{ github.event.inputs.company_code }}" "${{ github.event.inputs.start_date }}"
